config/routes.rb
Rails.application.routes.draw do
  resources :registrations
  resources :logins
  resources :posts, only: [:edit, :update, :new, :create]
  get 'posts/index', to: 'posts#index'
  get  '/posts/:id', to: 'posts#show'
  post '/posts/new', to: 'posts#create'
  # get 'dashboards/index', as: :dashboards
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
  end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    validates :title, presence: true
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    validates :password, presence: true
    has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  helper_method :current_user

    def current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end    
 
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless user
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    def new
        user = User.find_by(id: session[:user_id])
        redirect_to dashboards_path if user
        @user = User.new
    end

    def create
        @user = User.find_by(login_params)

        if @user
            session[:user_id] = @user.id
            redirect_to new_post_path	
        else
            flash[:alert] = "Email or password is wrong!"
            render :new, status: :unprocessable_entity
        end    
    end
    
    private

        def login_params
            params.require(:user).permit(:email, :password)
        end    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController  

  def index
    @posts = Post.all  
  end  

  def show
    @post = Post.find(params[:id])  
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user = Current.user
    if @post.save
      flash[:notice] = "Article was successfully created"
      redirect_to new_post_path
   else
    flash[:notice] = "You do not have permission to create posts"
    redirect_to posts_index_path
   end
  end

  def edit
    @post = Post.find(params[:id])
  end  

  def update
    @post = Post.find(params[:id])
    if @post.user == current_user 
      @post.update(post_params)
      flash[:notice] = "Article was successfully updated!"
      redirect_to posts_index_path
    else
      redirect_to '/index'
      flash[:notice] = "you do not have permissions to update this post!"
    end  
   
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_login_path
    else
      flash[:alert] = "Couldn't save the User :("
      render :new, status: :unprocessable_entity
    end  

  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/index.html.erb
<h1>Welcome to you Dashboard</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/css/foundation.min.css" crossorigin="anonymous">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>
      <div id= "content">
      <%= yield %>
      </div>
  </body>
</html>

app/views/logins/new.html.erb
<h1> Login </h1>

<%= form_with model: @user, url: logins_path do |form| %>
    <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>
    <div>
        <%= form.label :password %>
        <%= form.password_field :password %>
    </div>
    <div>
        <%= form.submit "Log in" %>
    </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>

app/views/posts/edit.html.erb
<h1> Update Post </h1>
<%= form_with model: @post do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>
    <div>
        <%= form.submit "Update" %>
    </div>

<% end %>
<%= link_to "Back to all posts", posts_index_path %> 

app/views/posts/index.html.erb
<h1>A list of posts</h1>
<div class = "button">
    <%= link_to "Create a new post", new_post_path %> 
</div>
<div>
<% @posts.each do |post| %>
    <ul>
        <h3><%= post.title %></h2>
        <p><%= post.body %></p>
        <span><%= post.user.email%></span>
        <br>
        <span><%= link_to "View", post_path(post) %>
        <% if post.user == Current.user%>
            <span><%= link_to "edit", edit_post_path(post) %>
        <% end %>
    </ul>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= form_with model: @post, url: new_post_path do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>
    <div>
        <%= form.submit "Create" %>
    </div>
<% end %>
<%= link_to "Back to all posts", posts_index_path %> 

app/views/posts/show.erb
<h1>View post</h1>
        <h2><%= @post.title %></h2>
        <p><%= @post.body %></p>
        <span><%= @post.user.email%></span>
        <br>
        <%= link_to "Back to all posts", posts_index_path %> 
    </ul>